# Generated by Django 3.2.4 on 2021-08-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_unit', models.CharField(max_length=3)),
                ('price', models.FloatField(default=0)),
                ('duration_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('price_id', models.CharField(blank=True, max_length=50, null=True)),
                ('related_image', models.FileField(blank=True, null=True, upload_to='products')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
